# Generated by Django 6.0.6 on 2026-07-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0002_alter_demoimport_options_demoimport_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="demoimport",
            name="label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="A name for this import (shown while it runs).",
                max_length=100,
                verbose_name="Label",
            ),
        ),
    ]
