# Generated by Django 6.0.6 on 2026-07-03 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_demoimport_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainEnd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('started_on', models.DateTimeField(blank=True, null=True)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('finished_successfully', models.BooleanField(default=False)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('result_context', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='', max_length=20)),
                ('status_text', models.CharField(blank=True, default='', max_length=255)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('log', models.JSONField(default=list)),
                ('log_seq', models.PositiveIntegerField(default=0)),
                ('current_stage', models.IntegerField(default=-1)),
                ('stage_states', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChainStart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('started_on', models.DateTimeField(blank=True, null=True)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('finished_successfully', models.BooleanField(default=False)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('result_context', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='', max_length=20)),
                ('status_text', models.CharField(blank=True, default='', max_length=255)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('log', models.JSONField(default=list)),
                ('log_seq', models.PositiveIntegerField(default=0)),
                ('current_stage', models.IntegerField(default=-1)),
                ('stage_states', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FailingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('started_on', models.DateTimeField(blank=True, null=True)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('finished_successfully', models.BooleanField(default=False)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('result_context', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='', max_length=20)),
                ('status_text', models.CharField(blank=True, default='', max_length=255)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('log', models.JSONField(default=list)),
                ('log_seq', models.PositiveIntegerField(default=0)),
                ('current_stage', models.IntegerField(default=-1)),
                ('stage_states', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuickTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('started_on', models.DateTimeField(blank=True, null=True)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('finished_successfully', models.BooleanField(default=False)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('result_context', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='', max_length=20)),
                ('status_text', models.CharField(blank=True, default='', max_length=255)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('log', models.JSONField(default=list)),
                ('log_seq', models.PositiveIntegerField(default=0)),
                ('current_stage', models.IntegerField(default=-1)),
                ('stage_states', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RedirectingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('started_on', models.DateTimeField(blank=True, null=True)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('finished_successfully', models.BooleanField(default=False)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('result_context', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='', max_length=20)),
                ('status_text', models.CharField(blank=True, default='', max_length=255)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('log', models.JSONField(default=list)),
                ('log_seq', models.PositiveIntegerField(default=0)),
                ('current_stage', models.IntegerField(default=-1)),
                ('stage_states', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
